### ISSUE TITLE
passing an mpid above 2.1 billion to mpidinfo.py causes ProgrammingError to be raised

### ISSUE THREAD

**Issue by coleslaw481** [CRBS/ncmirtools#9]
$ mpidinfo.py 2200000000
2017-01-12 16:15:21,966 ERROR ncmirtools.mpidinfo Error caught exception
Traceback (most recent call last):
  File "/usr/bin/mpidinfo.py", line 62, in _run_search_database
    res = search.get_microscopyproduct_for_id(mpid)
  File "/usr/lib/python2.7/site-packages/ncmirtools/lookup.py", line 419, in get_microscopyproduct_for_id
    "WHERE mpid='" + str(mpid) + "'")
  File "/home/churas/.local/lib/python2.7/site-packages/pg8000/core.py", line 906, in execute
    self._c.execute(self, operation, args)
  File "/home/churas/.local/lib/python2.7/site-packages/pg8000/core.py", line 1940, in execute
    self.handle_messages(cursor)
  File "/home/churas/.local/lib/python2.7/site-packages/pg8000/core.py", line 2088, in handle_messages
    raise self.error
ProgrammingError: (u'ERROR', u'22003', u'value "2200000000" is out of range for type integer', u'65', u'numutils.c', u'75', u'pg_atoi', u'', u'')

Looks like max microscopy id is 2147483647.  Not sure if we should make this error pretty by catching it and wrapping it with more friendly message or just not allowing large numbers to be used...

**Comment by coleslaw481** [comment]
Fixed by adding type check in MicroscopyProductLookupViaDatabase.get_microscopyproduct_for_id() as well as a check that id is not greater then 2^31 -1
